NumPy - Numerical Python
- Allow several mathematical operation including matrix
- Faster operation

In [1]:
import numpy as np

In [3]:
# campare python list and numpy list
from time import process_time
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
total_time = end_time - start_time
print(total_time)

0.0017932220000003163


In [4]:
from time import process_time
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
total_time = end_time - start_time
print(total_time)

0.0007903159999997911


# NumPy Arrays

In [5]:
# list
list1 = np.array([1,2,3,4,5])
type(list1)

numpy.ndarray

In [6]:
# creating 1d array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [12]:
# creating 2d array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)
c.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

In [14]:
# Creating a array of zeros
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# create a array of ones
e = np.ones((3,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# array of a perticular value
f = np.full((3,4),5.2)
print(f)

[[5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]]


In [20]:
# create a identity matrix
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# creating a array of random values
x = np.random.random((3,4))
print(x)

[[0.21901821 0.87315763 0.81591977 0.8283121 ]
 [0.2019188  0.68725442 0.81380841 0.88489825]
 [0.59456008 0.94864234 0.0858034  0.73677449]]


In [24]:
# random intiger value array within a specific range
y = np.random.randint(10,99,(3,4))
print(y)


[[43 36 13 27]
 [16 38 90 49]
 [65 32 88 60]]


In [28]:
# array with evenly space values -- specifiying the number of value required
z = np.linspace(10,100,5)
print(z)

[ 10.   32.5  55.   77.5 100. ]


In [29]:
# array with evenly space values -- specifing the step
z = np.arange(10,100,5)
print(z)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [32]:
# converting a list to numpy array
list1 = [1,2,4,5,0]
list2 = np.asarray((list1))
print(list2)
print(type(list1))
print(type(list2))

[1 2 4 5 0]
<class 'list'>
<class 'numpy.ndarray'>


# Analyzing NumPy array

In [33]:
a = np.random.randint(10,90,(5,5))
print(a)

[[62 86 88 89 88]
 [46 57 10 36 16]
 [17 89 21 11 22]
 [35 43 23 63 10]
 [76 47 83 60 89]]


In [34]:
# number of dimention
print(a.ndim)

2


In [35]:
# number of element of a array
print(a.size)

25


In [36]:
# checking the detatype
print(a.dtype)

int64


# Mathematical operation

In [37]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
print(a+b)

[[2 1 3]
 [2 8 8]
 [1 7 4]]
[[7 6 5]
 [7 8 4]
 [1 7 4]]
[[ 9  7  8]
 [ 9 16 12]
 [ 2 14  8]]


In [38]:
print(a-b)

[[-5 -5 -2]
 [-5  0  4]
 [ 0  0  0]]


In [39]:
print(a*b)

[[14  6 15]
 [14 64 32]
 [ 1 49 16]]


In [40]:
print(a/b)

[[0.28571429 0.16666667 0.6       ]
 [0.28571429 1.         2.        ]
 [1.         1.         1.        ]]


# Array Manipulation

In [41]:
a = np.random.randint(1,10,(2,3))

In [42]:
# transpose
trans = np.transpose(a)
print(trans)

[[7 8]
 [9 9]
 [8 2]]


In [44]:
# reshaping a array
a = np.random.randint(1,10,(2,3))
b = a.reshape(3,2)
print(a)
print(b)

[[5 9 2]
 [4 5 2]]
[[5 9]
 [2 4]
 [5 2]]
